# github.com/roadrunner-server/roadrunner version
[roadrunner]
ref = "master"

[github_token]
token = "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"

[log]
level = "debug"
mode = "development"

[plugins]
# ref -> master, commit or tag
http = { ref = "master", owner = "roadrunner-server", repository = "http" }
logger = { ref = "master", owner = "roadrunner-server", repository = "logger" }
server = { ref = "master", owner = "roadrunner-server", repository = "server" }
rpc = { ref = "master", owner = "roadrunner-server", repository = "rpc" }