[velox]
build_args = "-ldflag -s -race"

[roadrunner]
ref = "master"

[github_token]
token = "fooooo"

[log]
level = "debug"
mode = "development"

[plugins]
# ref -> master, commit or tag
temporal = { ref = "master", owner = "temporalio", repository = "roadrunner-temporal" }
http = { ref = "v2.8.0-rc.3", owner = "roadrunner-server", repository = "http" }
logger = { ref = "master", owner = "roadrunner-server", repository = "logger" }
server = { ref = "master", owner = "roadrunner-server", repository = "server" }
service = { ref = "master", owner = "roadrunner-server", repository = "service", replace = "../plugins/service" }
rpc = { ref = "master", owner = "roadrunner-server", repository = "rpc" }