[velox]
build_args = ['-trimpath', '-ldflags', '-s -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.version=${VERSION} -X github.com/roadrunner-server/roadrunner/v2023/internal/meta.buildTime=${TIME}']

[roadrunner]
ref = "v2023.1.0-alpha.2"

[github]
    [github.token]
    token = "${RT_TOKEN}"

    [github.plugins]
    # LOGS
    appLogger = { ref = "v4.0.2", owner = "roadrunner-server", repository = "app-logger" }
    logger = { ref = "v4.1.0", owner = "roadrunner-server", repository = "logger" }

    # CENTRIFUGE BROADCASTING PLATFORM
    centrifuge = { ref = "v4.0.3", owner = "roadrunner-server", repository = "centrifuge" }

    # WORKFLOWS ENGINE
    temporal = { ref = "v4.0.0", owner = "temporalio", repository = "roadrunner-temporal" }

    # METRICS
    metrics = { ref = "v4.0.2", owner = "roadrunner-server", repository = "metrics" }

    # SERVER
    server = { ref = "v4.0.2", owner = "roadrunner-server", repository = "server" }


    # JOBS
    jobs = { ref = "v4.2.2", owner = "roadrunner-server", repository = "jobs" }
    amqp = { ref = "v4.3.2", owner = "willypuzzle", repository = "amqp" }
[log]
    level = "debug"
    mode = "development"
