[velox]
build_args = ['-trimpath', '-ldflags', '-s -X github.com/roadrunner-server/roadrunner/v2/internal/meta.version=${VERSION} -X github.com/roadrunner-server/roadrunner/v2/internal/meta.buildTime=${TIME}']

[roadrunner]
ref = "master"

[github]
    [github.token]
    token = "${RT_TOKEN}"

    # ref -> master, commit or tag
    [github.plugins]
    # LOGS
    appLogger = { ref = "master", owner = "roadrunner-server", repository = "app-logger" }
    logger = { ref = "master", owner = "roadrunner-server", repository = "logger" }

    # CENTRIFUGE BROADCASTING PLATFORM
    centrifuge = { ref = "master", owner = "roadrunner-server", repository = "centrifuge" }

    # WORKFLOWS ENGINE
    temporal = { ref = "master", owner = "temporalio", repository = "roadrunner-temporal" }

    # METRICS
    metrics = { ref = "master", owner = "roadrunner-server", repository = "metrics" }

    # HTTP + MIDDLEWARE
    http = { ref = "master", owner = "roadrunner-server", repository = "http" }
    gzip = { ref = "master", owner = "roadrunner-server", repository = "gzip" }
    prometheus = { ref = "master", owner = "roadrunner-server", repository = "prometheus" }
    headers = { ref = "master", owner = "roadrunner-server", repository = "headers" }
    static = { ref = "master", owner = "roadrunner-server", repository = "static" }
    cache = { ref = "v1.6.22", owner = "darkweak", repository = "souin", folder="plugins/roadrunner" }
    otel = { ref = "master", owner = "roadrunner-server", repository = "otel" }

    # RELOAD (for the DEV)
    reload = { ref = "master", owner = "roadrunner-server", repository = "reload" }

    # SERVER
    server = { ref = "master", owner = "roadrunner-server", repository = "server" }

    # SERVICE aka lightweit systemd
    service = { ref = "master", owner = "roadrunner-server", repository = "service" }

    # JOBS
    jobs = { ref = "master", owner = "roadrunner-server", repository = "jobs" }
    amqp = { ref = "master", owner = "roadrunner-server", repository = "amqp" }
    sqs = { ref = "master", owner = "roadrunner-server", repository = "sqs" }
    beanstalk = { ref = "master", owner = "roadrunner-server", repository = "beanstalk" }
    nats = { ref = "master", owner = "roadrunner-server", repository = "nats" }
    kafka = { ref = "master", owner = "roadrunner-server", repository = "kafka" }

    # KV
    kv = { ref = "master", owner = "roadrunner-server", repository = "kv" }
    boltdb = { ref = "master", owner = "roadrunner-server", repository = "boltdb" }
    memory = { ref = "master", owner = "roadrunner-server", repository = "memory" }
    redis = { ref = "master", owner = "roadrunner-server", repository = "redis" }
    memcached = { ref = "master", owner = "roadrunner-server", repository = "memcached" }

    # FILESERVER (static files)
    fileserver = { ref = "master", owner = "roadrunner-server", repository = "fileserver" }

    # gRPC plugin
    grpc = { ref = "master", owner = "roadrunner-server", repository = "grpc" }

    # HEALTHCHECKS + READINESS CHECKS
    status = { ref = "master", owner = "roadrunner-server", repository = "status" }

    # TCP for the RAW TCP PAYLOADS
    tcp = { ref = "master", owner = "roadrunner-server", repository = "tcp" }

[gitlab]
    [gitlab.token]
    # api, read-api, read-repo
    token = "${GL_TOKEN}"

    [gitlab.endpoint]
    endpoint = "https://gitlab.com"

    [gitlab.plugins]
    # ref -> master, commit or tag
    test_plugin_1 = { ref = "main", owner = "rustatian", repository = "36405203" }
    test_plugin_2 = { ref = "main", owner = "rustatian", repository = "36405235" }

[log]
level = "debug"
mode = "development"